name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: lists
      run: ls
    - name: compile
      run: g++ -std=c++17 -Wall main.cpp -o main
    - name: run
      run: ./main 10
    - name: clean
      run: rm main
