name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        git submodule init
        cd Test
        g++ -std=c++17 main.cpp -o main
        ./main 10 > example_out.txt
        rm main
    - name: Commit files
      if: github.event.commits[0].message != 'Commit Example'
      run: |
        git config --global user.email "icy-bot@users.noreply.github.com"
        git config --global user.name "Borworntat Dendumrongkul"
        git add .
        git commit -m "Commit Example" -a
    - name: Push changes
      if: github.event.commits[0].message != 'Commit Example'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: main
